version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ~/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address :9001 /data

#    docker run -p 9000:9000 -p 9001:9001 --name minio -d -v ~/minio/data:/data -e "MINIO_ROOT_USER=minio" -e "MINIO_ROOT_PASSWORD=minio123" minio/minio server --console-address :9001 /data

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow 
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ~/git/dags:/opt/airflow/dags #./dags:/opt/airflow/dags
      - ~/git/logs:/opt/airflow/logs
      - ~/git/plugins:/opt/airflow/plugins
      - ~/git/data:/opt/airflow/data
    restart: always
    command: >
      bash -c "airflow db upgrade && 
      airflow users create --username admin --password admin --firstname FIRST_NAME --lastname LAST_NAME --role Admin --email admin@example.com && 
      airflow webserver"

  scheduler:
    image: apache/airflow:latest
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ~/git/dags:/opt/airflow/dags
      - ~/git/logs:/opt/airflow/logs
      - ~/git/plugins:/opt/airflow/plugins
      - ~/git/data:/opt/airflow/data
    restart: always
    command: >
      bash -c "sleep 30 &&
      airflow scheduler"

  dbt:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ~/.dbt:/root/.dbt
      - ~/git/app:/dbt
    command: ["run"]

      